# Setup
title:               Yonsei MLSys
tagline:             'Student Group'
description:         'Yonsei MLSys Student Group'
url:                 https://yonsei-mlsys.github.io
baseurl:             ''
paginate:            1000
permalink:           pretty
future: true
published: true


# About/contact
author:
  name:              Yonsei MLSys
  url:               https://yonsei-mlsys.github.io
  email:             kiung@yonsei.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
